spring.datasource.url=jdbc:mysql://localhost:3306/test_blog_engine?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1235
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
captcha.lifetime.hour=1