spring.datasource.url=jdbc:mysql://localhost:3306/booklib?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1235
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true